version: "3.8"

services:
  db:
    image: postgres:13
    container_name: fun-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fundb
    ports:
      - "5432:5432"
    volumes:
      - fun-pgdata:/var/lib/postgresql/data

volumes:
  fun-pgdata:
